-- Seed top 100 US colleges

INSERT INTO colleges (name, short_name, city, state, usnews_rank, admissions_url) VALUES
('Princeton University', 'Princeton', 'Princeton', 'NJ', 1, 'https://admission.princeton.edu/'),
('Massachusetts Institute of Technology', 'MIT', 'Cambridge', 'MA', 2, 'https://admissions.mit.edu/'),
('Harvard University', 'Harvard', 'Cambridge', 'MA', 3, 'https://college.harvard.edu/admissions'),
('Stanford University', 'Stanford', 'Stanford', 'CA', 3, 'https://admission.stanford.edu/'),
('Yale University', 'Yale', 'New Haven', 'CT', 5, 'https://admissions.yale.edu/'),
('University of Pennsylvania', 'UPenn', 'Philadelphia', 'PA', 6, 'https://admissions.upenn.edu/'),
('California Institute of Technology', 'Caltech', 'Pasadena', 'CA', 7, 'https://www.admissions.caltech.edu/'),
('Duke University', 'Duke', 'Durham', 'NC', 7, 'https://admissions.duke.edu/'),
('Brown University', 'Brown', 'Providence', 'RI', 9, 'https://admission.brown.edu/'),
('Johns Hopkins University', 'JHU', 'Baltimore', 'MD', 9, 'https://apply.jhu.edu/'),
('Northwestern University', 'Northwestern', 'Evanston', 'IL', 9, 'https://admissions.northwestern.edu/'),
('Columbia University', 'Columbia', 'New York', 'NY', 12, 'https://undergrad.admissions.columbia.edu/'),
('Cornell University', 'Cornell', 'Ithaca', 'NY', 12, 'https://admissions.cornell.edu/'),
('University of Chicago', 'UChicago', 'Chicago', 'IL', 12, 'https://collegeadmissions.uchicago.edu/'),
('University of California, Berkeley', 'UC Berkeley', 'Berkeley', 'CA', 15, 'https://admissions.berkeley.edu/'),
('University of California, Los Angeles', 'UCLA', 'Los Angeles', 'CA', 15, 'https://admission.ucla.edu/'),
('Rice University', 'Rice', 'Houston', 'TX', 17, 'https://admission.rice.edu/'),
('Dartmouth College', 'Dartmouth', 'Hanover', 'NH', 18, 'https://admissions.dartmouth.edu/'),
('Vanderbilt University', 'Vanderbilt', 'Nashville', 'TN', 18, 'https://admissions.vanderbilt.edu/'),
('University of Notre Dame', 'Notre Dame', 'Notre Dame', 'IN', 20, 'https://admissions.nd.edu/'),
('University of Michigan, Ann Arbor', 'UMich', 'Ann Arbor', 'MI', 21, 'https://admissions.umich.edu/'),
('Georgetown University', 'Georgetown', 'Washington', 'DC', 22, 'https://uadmissions.georgetown.edu/'),
('University of North Carolina at Chapel Hill', 'UNC', 'Chapel Hill', 'NC', 22, 'https://admissions.unc.edu/'),
('Carnegie Mellon University', 'CMU', 'Pittsburgh', 'PA', 24, 'https://admission.enroll.cmu.edu/'),
('Emory University', 'Emory', 'Atlanta', 'GA', 24, 'https://apply.emory.edu/'),
('University of Virginia', 'UVA', 'Charlottesville', 'VA', 24, 'https://admission.virginia.edu/'),
('Washington University in St. Louis', 'WashU', 'St. Louis', 'MO', 24, 'https://admissions.wustl.edu/'),
('University of California, Davis', 'UC Davis', 'Davis', 'CA', 28, 'https://admissions.ucdavis.edu/'),
('University of California, San Diego', 'UCSD', 'La Jolla', 'CA', 28, 'https://admissions.ucsd.edu/'),
('University of Florida', 'UF', 'Gainesville', 'FL', 28, 'https://admissions.ufl.edu/'),
('University of Southern California', 'USC', 'Los Angeles', 'CA', 28, 'https://admission.usc.edu/'),
('University of Texas at Austin', 'UT Austin', 'Austin', 'TX', 32, 'https://admissions.utexas.edu/'),
('Georgia Institute of Technology', 'Georgia Tech', 'Atlanta', 'GA', 33, 'https://admission.gatech.edu/'),
('University of California, Irvine', 'UCI', 'Irvine', 'CA', 33, 'https://admissions.uci.edu/'),
('New York University', 'NYU', 'New York', 'NY', 35, 'https://www.nyu.edu/admissions.html'),
('University of California, Santa Barbara', 'UCSB', 'Santa Barbara', 'CA', 35, 'https://admissions.sa.ucsb.edu/'),
('University of Illinois Urbana-Champaign', 'UIUC', 'Champaign', 'IL', 35, 'https://admissions.illinois.edu/'),
('University of Wisconsin-Madison', 'UW-Madison', 'Madison', 'WI', 35, 'https://admissions.wisc.edu/'),
('Boston College', 'BC', 'Chestnut Hill', 'MA', 39, 'https://www.bc.edu/admission'),
('Rutgers University-New Brunswick', 'Rutgers', 'New Brunswick', 'NJ', 40, 'https://admissions.rutgers.edu/'),
('Tufts University', 'Tufts', 'Medford', 'MA', 40, 'https://admissions.tufts.edu/'),
('University of Washington', 'UW', 'Seattle', 'WA', 40, 'https://admit.washington.edu/'),
('Boston University', 'BU', 'Boston', 'MA', 43, 'https://www.bu.edu/admissions/'),
('Ohio State University', 'OSU', 'Columbus', 'OH', 43, 'https://admissions.osu.edu/'),
('Purdue University', 'Purdue', 'West Lafayette', 'IN', 43, 'https://admissions.purdue.edu/'),
('University of Maryland, College Park', 'UMD', 'College Park', 'MD', 46, 'https://admissions.umd.edu/'),
('Lehigh University', 'Lehigh', 'Bethlehem', 'PA', 47, 'https://admissions.lehigh.edu/'),
('Texas A&M University', 'Texas A&M', 'College Station', 'TX', 47, 'https://admissions.tamu.edu/'),
('University of Georgia', 'UGA', 'Athens', 'GA', 47, 'https://admissions.uga.edu/'),
('University of Rochester', 'Rochester', 'Rochester', 'NY', 47, 'https://enrollment.rochester.edu/admissions/'),
('Virginia Tech', 'VT', 'Blacksburg', 'VA', 47, 'https://admissions.vt.edu/'),
('Wake Forest University', 'Wake Forest', 'Winston-Salem', 'NC', 47, 'https://admissions.wfu.edu/'),
('Case Western Reserve University', 'CWRU', 'Cleveland', 'OH', 53, 'https://admission.case.edu/'),
('Florida State University', 'FSU', 'Tallahassee', 'FL', 53, 'https://admissions.fsu.edu/'),
('Northeastern University', 'Northeastern', 'Boston', 'MA', 53, 'https://admissions.northeastern.edu/'),
('University of Minnesota, Twin Cities', 'UMN', 'Minneapolis', 'MN', 53, 'https://admissions.tc.umn.edu/'),
('William & Mary', 'W&M', 'Williamsburg', 'VA', 53, 'https://www.wm.edu/admission/'),
('Brandeis University', 'Brandeis', 'Waltham', 'MA', 58, 'https://www.brandeis.edu/admissions/'),
('North Carolina State University', 'NC State', 'Raleigh', 'NC', 58, 'https://admissions.ncsu.edu/'),
('Stony Brook University', 'Stony Brook', 'Stony Brook', 'NY', 58, 'https://www.stonybrook.edu/undergraduate-admissions/'),
('University of California, Merced', 'UC Merced', 'Merced', 'CA', 60, 'https://admissions.ucmerced.edu/'),
('University of California, Riverside', 'UC Riverside', 'Riverside', 'CA', 60, 'https://admissions.ucr.edu/'),
('University of California, Santa Cruz', 'UCSC', 'Santa Cruz', 'CA', 60, 'https://admissions.ucsc.edu/'),
('Penn State University', 'Penn State', 'University Park', 'PA', 60, 'https://admissions.psu.edu/'),
('University of Connecticut', 'UConn', 'Storrs', 'CT', 58, 'https://admissions.uconn.edu/'),
('University of Massachusetts Amherst', 'UMass', 'Amherst', 'MA', 67, 'https://www.umass.edu/admissions/'),
('University of Pittsburgh', 'Pitt', 'Pittsburgh', 'PA', 67, 'https://admissions.pitt.edu/'),
('George Washington University', 'GWU', 'Washington', 'DC', 67, 'https://undergraduate.admissions.gwu.edu/'),
('Syracuse University', 'Syracuse', 'Syracuse', 'NY', 67, 'https://admissions.syr.edu/'),
('University of Miami', 'Miami', 'Coral Gables', 'FL', 67, 'https://admissions.miami.edu/'),
('Indiana University Bloomington', 'IU', 'Bloomington', 'IN', 73, 'https://admissions.indiana.edu/'),
('Michigan State University', 'MSU', 'East Lansing', 'MI', 73, 'https://admissions.msu.edu/'),
('Pepperdine University', 'Pepperdine', 'Malibu', 'CA', 76, 'https://www.pepperdine.edu/admission/'),
('Tulane University', 'Tulane', 'New Orleans', 'LA', 73, 'https://admission.tulane.edu/'),
('University of Colorado Boulder', 'CU Boulder', 'Boulder', 'CO', 73, 'https://admissions.colorado.edu/'),
('University of Delaware', 'UDel', 'Newark', 'DE', 76, 'https://admissions.udel.edu/'),
('University of Iowa', 'Iowa', 'Iowa City', 'IA', 83, 'https://admissions.uiowa.edu/'),
('Villanova University', 'Villanova', 'Villanova', 'PA', 67, 'https://www1.villanova.edu/university/undergraduate-admission.html'),
('Rensselaer Polytechnic Institute', 'RPI', 'Troy', 'NY', 76, 'https://admissions.rpi.edu/'),
('Santa Clara University', 'SCU', 'Santa Clara', 'CA', 60, 'https://www.scu.edu/admission/'),
('Southern Methodist University', 'SMU', 'Dallas', 'TX', 76, 'https://www.smu.edu/admission'),
('University of Oregon', 'UO', 'Eugene', 'OR', 98, 'https://admissions.uoregon.edu/'),
('University of South Carolina', 'SC', 'Columbia', 'SC', 83, 'https://sc.edu/about/offices_and_divisions/undergraduate_admissions/'),
('Baylor University', 'Baylor', 'Waco', 'TX', 93, 'https://www.baylor.edu/admissions/'),
('Clemson University', 'Clemson', 'Clemson', 'SC', 76, 'https://www.clemson.edu/admissions/'),
('Colorado School of Mines', 'Mines', 'Golden', 'CO', 83, 'https://admissions.mines.edu/'),
('Fordham University', 'Fordham', 'New York', 'NY', 83, 'https://www.fordham.edu/admissions/'),
('Loyola Marymount University', 'LMU', 'Los Angeles', 'CA', 76, 'https://admission.lmu.edu/'),
('Marquette University', 'Marquette', 'Milwaukee', 'WI', 93, 'https://www.marquette.edu/admissions/'),
('Stevens Institute of Technology', 'Stevens', 'Hoboken', 'NJ', 76, 'https://www.stevens.edu/admissions'),
('University at Buffalo', 'UB', 'Buffalo', 'NY', 83, 'https://admissions.buffalo.edu/'),
('University of Arizona', 'Arizona', 'Tucson', 'AZ', 98, 'https://admissions.arizona.edu/'),
('University of San Diego', 'USD', 'San Diego', 'CA', 93, 'https://www.sandiego.edu/admissions/'),
('University of Tennessee', 'UTK', 'Knoxville', 'TN', 98, 'https://admissions.utk.edu/'),
('Worcester Polytechnic Institute', 'WPI', 'Worcester', 'MA', 83, 'https://www.wpi.edu/admissions'),
('Yeshiva University', 'YU', 'New York', 'NY', 76, 'https://www.yu.edu/admissions'),
('Auburn University', 'Auburn', 'Auburn', 'AL', 93, 'https://www.auburn.edu/admissions/'),
('Gonzaga University', 'Gonzaga', 'Spokane', 'WA', 93, 'https://www.gonzaga.edu/admission'),
('University of Kentucky', 'UK', 'Lexington', 'KY', 98, 'https://www.uky.edu/admission/')
ON CONFLICT (name) DO NOTHING;
