-- Seed US News ranks 99-200 colleges (2024-2025 rankings)

INSERT INTO colleges (name, short_name, city, state, usnews_rank, admissions_url) VALUES
-- Rank 99-105
('Drexel University', 'Drexel', 'Philadelphia', 'PA', 99, 'https://drexel.edu/undergrad/'),
('Loyola University Chicago', 'Loyola Chicago', 'Chicago', 'IL', 99, 'https://www.luc.edu/undergrad/'),
('Rochester Institute of Technology', 'RIT', 'Rochester', 'NY', 99, 'https://www.rit.edu/admissions/'),
('San Diego State University', 'SDSU', 'San Diego', 'CA', 99, 'https://admissions.sdsu.edu/'),
('SUNY College of Environmental Science and Forestry', 'SUNY ESF', 'Syracuse', 'NY', 99, 'https://www.esf.edu/admissions/'),
('Temple University', 'Temple', 'Philadelphia', 'PA', 99, 'https://admissions.temple.edu/'),
('University of Denver', 'DU', 'Denver', 'CO', 99, 'https://www.du.edu/admission-aid/'),
('University of New Hampshire', 'UNH', 'Durham', 'NH', 99, 'https://admissions.unh.edu/'),
('University of Oklahoma', 'OU', 'Norman', 'OK', 99, 'https://www.ou.edu/admissions/'),
('University of San Francisco', 'USF', 'San Francisco', 'CA', 99, 'https://www.usfca.edu/admission'),
('University of South Florida', 'USF', 'Tampa', 'FL', 99, 'https://www.usf.edu/admissions/'),
('University of Vermont', 'UVM', 'Burlington', 'VT', 99, 'https://www.uvm.edu/admissions/'),

-- Rank 111-120
('American University', 'AU', 'Washington', 'DC', 111, 'https://www.american.edu/admissions/'),
('Arizona State University', 'ASU', 'Tempe', 'AZ', 111, 'https://admission.asu.edu/'),
('Creighton University', 'Creighton', 'Omaha', 'NE', 111, 'https://admissions.creighton.edu/'),
('DePaul University', 'DePaul', 'Chicago', 'IL', 111, 'https://www.depaul.edu/admission-and-aid/'),
('Hofstra University', 'Hofstra', 'Hempstead', 'NY', 111, 'https://www.hofstra.edu/admission/'),
('Howard University', 'Howard', 'Washington', 'DC', 111, 'https://howard.edu/admission'),
('Iowa State University', 'Iowa State', 'Ames', 'IA', 111, 'https://www.admissions.iastate.edu/'),
('Kansas State University', 'K-State', 'Manhattan', 'KS', 111, 'https://www.k-state.edu/admissions/'),
('Rutgers University-Newark', 'Rutgers Newark', 'Newark', 'NJ', 111, 'https://admissions.newark.rutgers.edu/'),
('The New School', 'New School', 'New York', 'NY', 111, 'https://www.newschool.edu/admission/'),
('University of Alabama', 'Alabama', 'Tuscaloosa', 'AL', 111, 'https://admissions.ua.edu/'),
('University of Dayton', 'Dayton', 'Dayton', 'OH', 111, 'https://www.udayton.edu/apply/'),
('University of Kansas', 'KU', 'Lawrence', 'KS', 111, 'https://admissions.ku.edu/'),
('University of Missouri', 'Mizzou', 'Columbia', 'MO', 111, 'https://admissions.missouri.edu/'),
('University of Nebraska-Lincoln', 'Nebraska', 'Lincoln', 'NE', 111, 'https://admissions.unl.edu/'),
('University of St. Thomas', 'St. Thomas', 'St. Paul', 'MN', 111, 'https://www.stthomas.edu/admissions/'),
('University of the Pacific', 'Pacific', 'Stockton', 'CA', 111, 'https://www.pacific.edu/admission'),

-- Rank 127-140
('Clark University', 'Clark', 'Worcester', 'MA', 127, 'https://www.clarku.edu/admissions/'),
('Clarkson University', 'Clarkson', 'Potsdam', 'NY', 127, 'https://www.clarkson.edu/admissions'),
('Colorado State University', 'CSU', 'Fort Collins', 'CO', 127, 'https://admissions.colostate.edu/'),
('Illinois Institute of Technology', 'IIT', 'Chicago', 'IL', 127, 'https://www.iit.edu/admissions'),
('Louisiana State University', 'LSU', 'Baton Rouge', 'LA', 127, 'https://www.lsu.edu/admissions/'),
('Mercer University', 'Mercer', 'Macon', 'GA', 127, 'https://admissions.mercer.edu/'),
('Miami University', 'Miami OH', 'Oxford', 'OH', 127, 'https://miamioh.edu/admission/'),
('New Jersey Institute of Technology', 'NJIT', 'Newark', 'NJ', 127, 'https://admissions.njit.edu/'),
('Oregon State University', 'Oregon State', 'Corvallis', 'OR', 127, 'https://admissions.oregonstate.edu/'),
('Seton Hall University', 'Seton Hall', 'South Orange', 'NJ', 127, 'https://www.shu.edu/admissions/'),
('Texas Christian University', 'TCU', 'Fort Worth', 'TX', 127, 'https://admissions.tcu.edu/'),
('The Catholic University of America', 'CUA', 'Washington', 'DC', 127, 'https://www.catholic.edu/admission/'),
('University of Arkansas', 'Arkansas', 'Fayetteville', 'AR', 127, 'https://admissions.uark.edu/'),
('University of Cincinnati', 'UC', 'Cincinnati', 'OH', 127, 'https://admissions.uc.edu/'),
('University of Hawaii at Manoa', 'Hawaii', 'Honolulu', 'HI', 127, 'https://manoa.hawaii.edu/admissions/'),
('University of Houston', 'UH', 'Houston', 'TX', 127, 'https://uh.edu/admissions/'),
('University of La Verne', 'La Verne', 'La Verne', 'CA', 127, 'https://laverne.edu/admission/'),
('University of Mississippi', 'Ole Miss', 'University', 'MS', 127, 'https://admissions.olemiss.edu/'),
('University of Rhode Island', 'URI', 'Kingston', 'RI', 127, 'https://web.uri.edu/admission/'),
('Washington State University', 'WSU', 'Pullman', 'WA', 127, 'https://admission.wsu.edu/'),

-- Rank 147-160
('Adelphi University', 'Adelphi', 'Garden City', 'NY', 147, 'https://www.adelphi.edu/admissions/'),
('Belmont University', 'Belmont', 'Nashville', 'TN', 147, 'https://www.belmont.edu/admissions/'),
('George Mason University', 'GMU', 'Fairfax', 'VA', 147, 'https://www2.gmu.edu/admissions-aid'),
('Illinois State University', 'ISU', 'Normal', 'IL', 147, 'https://admissions.illinoisstate.edu/'),
('Quinnipiac University', 'Quinnipiac', 'Hamden', 'CT', 147, 'https://www.qu.edu/admissions/'),
('Samford University', 'Samford', 'Birmingham', 'AL', 147, 'https://www.samford.edu/admission/'),
('San Jose State University', 'SJSU', 'San Jose', 'CA', 147, 'https://www.sjsu.edu/admissions/'),
('Seattle University', 'Seattle U', 'Seattle', 'WA', 147, 'https://www.seattleu.edu/undergraduate-admissions/'),
('St. John Fisher University', 'Fisher', 'Rochester', 'NY', 147, 'https://www.sjf.edu/admissions/'),
('The University of Tulsa', 'Tulsa', 'Tulsa', 'OK', 147, 'https://admission.utulsa.edu/'),
('University at Albany', 'UAlbany', 'Albany', 'NY', 147, 'https://www.albany.edu/admissions'),
('University of Louisville', 'Louisville', 'Louisville', 'KY', 147, 'https://admissions.louisville.edu/'),
('University of Maine', 'Maine', 'Orono', 'ME', 147, 'https://go.umaine.edu/'),
('University of Massachusetts Lowell', 'UMass Lowell', 'Lowell', 'MA', 147, 'https://www.uml.edu/admissions/'),
('University of Montana', 'Montana', 'Missoula', 'MT', 147, 'https://admissions.umt.edu/'),
('University of North Carolina at Charlotte', 'UNC Charlotte', 'Charlotte', 'NC', 147, 'https://admissions.uncc.edu/'),
('University of North Texas', 'UNT', 'Denton', 'TX', 147, 'https://admissions.unt.edu/'),
('Virginia Commonwealth University', 'VCU', 'Richmond', 'VA', 147, 'https://admissions.vcu.edu/'),

-- Rank 165-180
('Ball State University', 'Ball State', 'Muncie', 'IN', 165, 'https://www.bsu.edu/admissions'),
('Binghamton University', 'Binghamton', 'Binghamton', 'NY', 165, 'https://www.binghamton.edu/admissions/'),
('Biola University', 'Biola', 'La Mirada', 'CA', 165, 'https://www.biola.edu/admissions'),
('Central Michigan University', 'CMU', 'Mount Pleasant', 'MI', 165, 'https://www.cmich.edu/offices-departments/admissions'),
('Chapman University', 'Chapman', 'Orange', 'CA', 165, 'https://www.chapman.edu/admission/'),
('Duquesne University', 'Duquesne', 'Pittsburgh', 'PA', 165, 'https://www.duq.edu/admissions/'),
('Fairfield University', 'Fairfield', 'Fairfield', 'CT', 165, 'https://www.fairfield.edu/undergraduate-admission/'),
('Kent State University', 'Kent State', 'Kent', 'OH', 165, 'https://www.kent.edu/admissions'),
('Lipscomb University', 'Lipscomb', 'Nashville', 'TN', 165, 'https://www.lipscomb.edu/admissions'),
('Marist College', 'Marist', 'Poughkeepsie', 'NY', 165, 'https://www.marist.edu/admission'),
('Missouri University of Science and Technology', 'Missouri S&T', 'Rolla', 'MO', 165, 'https://admissions.mst.edu/'),
('Ohio University', 'Ohio U', 'Athens', 'OH', 165, 'https://www.ohio.edu/admissions'),
('Oklahoma State University', 'OSU', 'Stillwater', 'OK', 165, 'https://admissions.okstate.edu/'),
('Pace University', 'Pace', 'New York', 'NY', 165, 'https://www.pace.edu/admission'),
('Portland State University', 'PSU', 'Portland', 'OR', 165, 'https://www.pdx.edu/admissions/'),
('Providence College', 'Providence', 'Providence', 'RI', 165, 'https://admission.providence.edu/'),
('Rutgers University-Camden', 'Rutgers Camden', 'Camden', 'NJ', 165, 'https://admissions.camden.rutgers.edu/'),
('Saint Louis University', 'SLU', 'St. Louis', 'MO', 165, 'https://www.slu.edu/admission/'),
('Suffolk University', 'Suffolk', 'Boston', 'MA', 165, 'https://www.suffolk.edu/admission'),
('SUNY Binghamton', 'SUNY Binghamton', 'Vestal', 'NY', 165, 'https://www.binghamton.edu/admissions/'),
('University of Alabama at Birmingham', 'UAB', 'Birmingham', 'AL', 165, 'https://www.uab.edu/students/admissions/'),
('University of Central Florida', 'UCF', 'Orlando', 'FL', 165, 'https://www.ucf.edu/admissions/'),
('University of Idaho', 'Idaho', 'Moscow', 'ID', 165, 'https://www.uidaho.edu/admissions'),
('University of Massachusetts Boston', 'UMass Boston', 'Boston', 'MA', 165, 'https://www.umb.edu/admissions'),
('University of Memphis', 'Memphis', 'Memphis', 'TN', 165, 'https://www.memphis.edu/admissions/'),
('University of Nevada, Las Vegas', 'UNLV', 'Las Vegas', 'NV', 165, 'https://www.unlv.edu/admissions'),
('University of Nevada, Reno', 'UNR', 'Reno', 'NV', 165, 'https://www.unr.edu/admissions'),
('University of North Carolina at Greensboro', 'UNCG', 'Greensboro', 'NC', 165, 'https://admissions.uncg.edu/'),
('University of North Dakota', 'UND', 'Grand Forks', 'ND', 165, 'https://und.edu/admissions/'),
('University of Texas at Dallas', 'UTD', 'Richardson', 'TX', 165, 'https://enroll.utdallas.edu/'),
('West Virginia University', 'WVU', 'Morgantown', 'WV', 165, 'https://admissions.wvu.edu/'),

-- Rank 196-200+
('Brigham Young University', 'BYU', 'Provo', 'UT', 115, 'https://enrollment.byu.edu/'),
('California Polytechnic State University', 'Cal Poly', 'San Luis Obispo', 'CA', 77, 'https://admissions.calpoly.edu/'),
('California State University, Long Beach', 'CSULB', 'Long Beach', 'CA', 196, 'https://www.csulb.edu/admissions'),
('California State University, Fullerton', 'CSUF', 'Fullerton', 'CA', 196, 'https://www.fullerton.edu/admissions/'),
('Embry-Riddle Aeronautical University', 'ERAU', 'Daytona Beach', 'FL', 196, 'https://admissions.erau.edu/'),
('Florida Atlantic University', 'FAU', 'Boca Raton', 'FL', 196, 'https://www.fau.edu/admissions/'),
('Florida International University', 'FIU', 'Miami', 'FL', 196, 'https://admissions.fiu.edu/'),
('James Madison University', 'JMU', 'Harrisonburg', 'VA', 196, 'https://www.jmu.edu/admissions/'),
('Simmons University', 'Simmons', 'Boston', 'MA', 196, 'https://www.simmons.edu/undergraduate/admission'),
('University of Massachusetts Dartmouth', 'UMass Dartmouth', 'North Dartmouth', 'MA', 196, 'https://www.umassd.edu/admissions/'),
('University of New Mexico', 'UNM', 'Albuquerque', 'NM', 196, 'https://admissions.unm.edu/'),
('University of North Carolina Wilmington', 'UNCW', 'Wilmington', 'NC', 196, 'https://uncw.edu/admissions/'),
('University of Texas at Arlington', 'UTA', 'Arlington', 'TX', 196, 'https://www.uta.edu/admissions/'),
('University of Texas at San Antonio', 'UTSA', 'San Antonio', 'TX', 196, 'https://www.utsa.edu/admissions/'),
('University of Wyoming', 'Wyoming', 'Laramie', 'WY', 196, 'https://www.uwyo.edu/admissions/')

ON CONFLICT (name) DO UPDATE SET
  usnews_rank = EXCLUDED.usnews_rank,
  admissions_url = EXCLUDED.admissions_url;
